# Generated by Django 5.0.3 on 2024-03-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=125)),
                ('company_name', models.CharField(max_length=300)),
                ('work_info', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('current_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('progress_percentage', models.CharField(max_length=100)),
                ('delivery_date', models.DateTimeField()),
                ('deal_amount', models.FloatField()),
            ],
        ),
    ]
